#!/bin/bash

set -e

echo "<html><head><style>body { margin: 0 };</style><body><canvas style='width: 100%; height: 100%'></canvas><script type=\"text/javascript\">$(cat build/bundle.js)</script></body></html>" > release/offline.html
