#!/bin/bash

set -e

echo "<html><head><style>body { margin: 0 }; canvas { width: 100%; height: 100% }</style><body><script type=\"text/javascript\">$(cat build/output/app.js)</script></body></html>" > release/offline.html
